steps:
  # 1. Build the Unified Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/automated-cognitive-dast:latest', 
      '-f', 'backend/Dockerfile.cloud', 
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'

  # 2. Push the Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/automated-cognitive-dast:latest']

  # 3. Build the Ephemeral ZAP Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/zap-mcp-server:latest', 
      '-f', 'Dockerfile.ephemeral', 
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'

  # 4. Push the Ephemeral ZAP Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zap-mcp-server:latest']

  # 5. Deploy Ephemeral Cloud Run Job (Example Definition)
  # Requires GEMINI_API_KEY to be set in environment or secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy zap-mcp-server-job \
          --image gcr.io/$PROJECT_ID/zap-mcp-server:latest \
          --region us-central1 \
          --memory 4Gi \
          --cpu 2 \
          --task-timeout 1800 \
          --max-retries 0 \
          --service-account=${_SERVICE_ACCOUNT} \
          --set-secrets=/config/llm_config.json=llm_config:latest \
          --set-env-vars=REPORTS_DIR=/home/zap/reports,GCS_REPORT_BUCKET=${_GCS_REPORT_BUCKET}

  # 3. Deploy Persistent Service (Web App)
  # Uses default CMD (./start_service.sh)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy automated-cognitive-dast-service \
          --image gcr.io/$PROJECT_ID/automated-cognitive-dast:latest \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8080 \
          --memory 4Gi \
          --cpu 2 \
          --max-instances 1 \
          --timeout 900 \
          --no-cpu-throttling
          # Memory/CPU boost for ZAP

  # 4. Deploy/Update Ephemeral Job definition
  # Uses overridden CMD (./start_job.sh)
  # Note: This creates the JOB definition. To run it, you use `gcloud run jobs execute ...`
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy automated-cognitive-dast-job \
          --image gcr.io/$PROJECT_ID/automated-cognitive-dast:latest \
          --region us-central1 \
          --command ./start_job.sh \
          --memory 2Gi \
          --cpu 2 \
          --task-timeout 1800

images:
  - 'gcr.io/$PROJECT_ID/automated-cognitive-dast:latest'
  - 'gcr.io/$PROJECT_ID/zap-mcp-server:latest'
